In [20]:
%load_ext lab_black
%config Completer.use_jedi = False
import pandas as pd
from Tuning_arithmetic_RSV_GridNumber import grid_trading, speedy_grid_trading
from tqdm import tqdm
import time

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black

In [21]:
%%time

# FILENAME = "Binance_BTC_1m.csv"
# data = pd.read_csv(FILENAME)
# optimization_arithmetic=[]
# for interval_for_bounds in tqdm(range(5,20)):
#     for sd in range(2,5):
#         records_df, final_profit = speedy_grid_trading(
#             data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
#         )
#         optimization_arithmetic.append([final_profit, "", interval_for_bounds, sd])

Wall time: 0 ns

In [22]:
%%time
# FILENAME = "Mild_Fluctuate_data.csv"
# FILENAME = "Increasing_Data.csv"
# FILENAME = "Binance_BTC_1m.csv"
FILENAME = "Decreasing_Data.csv"
data = pd.read_csv(FILENAME)
data
# optimization_RSV=[]
# for interval_for_rsv in tqdm(range(10, 60,5)):
#     for interval_for_bounds in range(5, 20,5):
#         for sd_parameter in range(2,5):
#             for grid_number in range(6, 40,4):
#                 records_df, final_profit = grid_trading(
#                     data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,GRID_NUMBER=grid_number
#                 )
#                 optimization_RSV.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter, grid_number])
#                 print(time.ctime())
# for grid_number in range(6, 40,4):
#     records_df, final_profit = grid_trading(
#         data, INTERVALS_FOR_RSV=30, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,GRID_NUMBER=grid_number
#     )
#     optimization_RSV.append([final_profit, 30, 15, 2, grid_number])
#     print(time.ctime())

Wall time: 15 ms

,Unnamed: 0,Unnamed: 0.1,TimeStamp,Open,High,Low,Close,Volume
0,127500,136740,2021/2/22 7:32,57472.29,57480.01,57437.93,57448.37,38.845894
1,127501,136741,2021/2/22 7:33,57447.38,57510.00,57446.01,57461.22,42.609888
2,127502,136742,2021/2/22 7:34,57461.21,57474.28,57448.93,57453.74,16.395970
3,127503,136743,2021/2/22 7:35,57453.74,57490.62,57441.13,57449.54,28.681314
4,127504,136744,2021/2/22 7:36,57449.41,57507.87,57449.41,57495.82,42.027890
...,...,...,...,...,...,...,...,...
9995,137495,109374,2021/2/3 6:07,35657.91,35665.27,35635.51,35640.62,20.562739
9996,137496,109375,2021/2/3 6:08,35637.32,35690.00,35637.32,35644.35,31.650692
9997,137497,109376,2021/2/3 6:09,35642.89,35660.95,35642.88,35655.41,22.989269
9998,137498,109377,2021/2/3 6:10,35655.41,35656.62,35611.25,35613.14,23.330931
9999,137499,109378,2021/2/3 6:11,35613.14,35624.21,35584.33,35587.97,30.461753

In [4]:
# optimization_df = pd.DataFrame(
#     optimization_RSV,
#     columns=[
#         "FinalProfit",
#         "IntervalForRSV",
#         "IntervalForBounds",
#         "SDParameter",
#         "GridNumber",
#     ],
# )

In [5]:
# optimization_df.to_excel("Training_ArithmeticSequence_RSV_GridNumber_Updated.xlsx")
# optimization_df = pd.read_excel("Training_ArithmeticSequence_RSV_GridNumber.xlsx")
# optimization_df

In [6]:
# df = optimization_df[
#     optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
# ]
# SDParameter = df["SDParameter"].unique()
# IntervalForBounds = df["IntervalForBounds"].unique()
# IntervalForRSV = df["IntervalForRSV"].unique()
# FinalProfit = df["FinalProfit"].unique()
# GridNumber = df["GridNumber"].unique()

In [8]:
# sd = SDParameter
# sd

In [9]:
# ifb = IntervalForBounds
# ifb

In [10]:
# ifrsv = IntervalForRSV
# ifrsv

In [11]:
# fp = FinalProfit
# fp

In [12]:
# gn = GridNumber
# gn

In [34]:
FILENAME = "Decreasing_Data.csv"
data = pd.read_csv(FILENAME)
data

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,TimeStamp,Open,High,Low,Close,Volume
0,5000,125000,135620,2021/2/21 12:52,56530.69,56571.77,56523.90,56526.38,17.928238
1,5001,125001,135621,2021/2/21 12:53,56526.38,56590.00,56517.00,56550.01,25.635945
2,5002,125002,135622,2021/2/21 12:54,56550.00,56640.00,56542.94,56604.54,19.254883
3,5003,125003,135623,2021/2/21 12:55,56604.55,56613.83,56541.25,56569.16,18.708440
4,5004,125004,135624,2021/2/21 12:56,56572.71,56631.11,56544.52,56623.46,19.152437
...,...,...,...,...,...,...,...,...,...
14995,19995,139995,113194,2021/2/5 21:47,37963.72,37999.68,37963.71,37978.09,89.867376
14996,19996,139996,113195,2021/2/5 21:48,37978.08,38130.17,37971.29,38130.00,178.493656
14997,19997,139997,113196,2021/2/5 21:49,38127.43,38198.78,38084.69,38172.03,211.731013
14998,19998,139998,113197,2021/2/5 21:50,38172.02,38172.03,38079.23,38140.94,158.094804
14999,19999,139999,113198,2021/2/5 21:51,38137.56,38141.20,38075.29,38110.48,92.377754

In [32]:
%%time
from Tuning_arithmetic_RSV_GridNumber import grid_trading, speedy_grid_trading
records_df, final_profit = grid_trading(
    data, INTERVALS_FOR_RSV=30, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,GRID_NUMBER=6,
)
records_df["Hour"] = pd.to_datetime(records_df["Hour"])
records_df

Wall time: 15 ms

,Action,Price,n,Cash,Profit,LowerBound,UpperBound,LowerGrid,UpperGrid,Hour
0,Buying,49180,2.0,1640,-98360,39090.312214,60231.227947,6190.167494,856.804417,2021-02-25 03:51:00
1,Selling,50323,0.0,102286,2286,39231.130653,60232.257958,6046.907756,953.468012,2021-02-25 09:35:00
2,Buying,50869,2.0,548,-99452,39231.660411,60232.302571,5981.395197,1018.818856,2021-02-25 09:36:00
3,Selling,53709,0.0,107965,7965,32538.423397,56310.575388,5154.825852,2769.224812,2021-03-10 00:30:00
4,Buying,54290,1.0,53675,-46325,32538.858708,56309.828616,4369.716595,3553.940041,2021-03-10 00:31:00
5,Selling,54775,0.0,108450,8450,32673.162051,56073.718030,7800.185326,0.000000,2021-03-10 18:04:00
6,Buying,55307,1.0,53143,-46857,32673.109772,56073.811013,7800.233747,0.000000,2021-03-10 18:05:00
7,Selling,55644,0.0,108787,8787,32667.772712,56087.543005,7806.590098,0.000000,2021-03-10 22:10:00
8,Buying,56068,1.0,52719,-47281,32666.896286,56089.230343,7807.444686,0.000000,2021-03-10 22:12:00
9,Selling,56348,0.0,109067,9067,32511.944448,56505.628840,7997.894797,0.000000,2021-03-11 01:36:00

In [33]:
%%time
import numpy as np

# records_df = records_df.sort_values(by="Hour", ascending=True)
records_df["TransactionInterval"] = records_df["Hour"].diff()
records_df = records_df.dropna()
records_df.loc[:, "TransactionInterval"] = records_df["TransactionInterval"].apply(
    lambda x: x.seconds
)
records_df

Wall time: 6 ms

C:\Users\bizjun\Anaconda3\envs\AlgoTrading\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

,Action,Price,n,Cash,Profit,LowerBound,UpperBound,LowerGrid,UpperGrid,Hour,TransactionInterval
1,Selling,50323,0.0,102286,2286,39231.130653,60232.257958,6046.907756,953.468012,2021-02-25 09:35:00,20640
2,Buying,50869,2.0,548,-99452,39231.660411,60232.302571,5981.395197,1018.818856,2021-02-25 09:36:00,60
3,Selling,53709,0.0,107965,7965,32538.423397,56310.575388,5154.825852,2769.224812,2021-03-10 00:30:00,53640
4,Buying,54290,1.0,53675,-46325,32538.858708,56309.828616,4369.716595,3553.940041,2021-03-10 00:31:00,60
5,Selling,54775,0.0,108450,8450,32673.162051,56073.718030,7800.185326,0.000000,2021-03-10 18:04:00,63180
6,Buying,55307,1.0,53143,-46857,32673.109772,56073.811013,7800.233747,0.000000,2021-03-10 18:05:00,60
7,Selling,55644,0.0,108787,8787,32667.772712,56087.543005,7806.590098,0.000000,2021-03-10 22:10:00,14700
8,Buying,56068,1.0,52719,-47281,32666.896286,56089.230343,7807.444686,0.000000,2021-03-10 22:12:00,120
9,Selling,56348,0.0,109067,9067,32511.944448,56505.628840,7997.894797,0.000000,2021-03-11 01:36:00,12240

In [50]:
# records_df.to_excel("TransactionHistory_ArithmeticSequence_RSV_GridNumber.xlsx")