In [1]:
%load_ext lab_black
%config Completer.use_jedi = False
import pandas as pd
from tqdm import tqdm
import time
import numpy as np

In [6]:
def calc_ATRP(high, low, close, n=15 * 24 * 60):
    high_low = high - low
    high_cp = np.abs(high - close.shift())
    low_cp = np.abs(low - close.shift())

    df = pd.concat([high_low, high_cp, low_cp], axis=1)
    true_range = np.max(df, axis=1)
    average_true_range = true_range.rolling(n).mean()
    average_true_range_percentage = average_true_range / close

    return average_true_range_percentage


##显示ATRP数值
FILENAME = "Binance_BTC_1m.csv"
data = pd.read_csv(FILENAME)
ATRP = calc_ATRP(data["High"], data["Low"], data["Close"])
data["ATRP"] = ATRP
data

,Unnamed: 0,TimeStamp,Open,High,Low,Close,Volume,ATRP
0,517,2020/11/19 10:00,17855.50,17939.55,17854.26,17907.59,414.673918,NaN
1,518,2020/11/19 10:01,17907.59,17941.59,17891.30,17923.53,173.585510,NaN
2,519,2020/11/19 10:02,17923.53,17944.69,17910.50,17926.59,112.092070,NaN
3,520,2020/11/19 10:03,17926.59,17937.26,17915.50,17919.95,72.432187,NaN
4,521,2020/11/19 10:04,17919.96,17926.86,17892.96,17924.51,138.997232,NaN
...,...,...,...,...,...,...,...,...
247336,245799,2021/5/9 9:55,59036.20,59059.18,59029.48,59053.52,21.634121,0.001227
247337,245800,2021/5/9 9:56,59053.52,59086.21,59031.07,59031.08,33.719035,0.001228
247338,245801,2021/5/9 9:57,59031.08,59057.70,59028.00,59051.93,30.339184,0.001227
247339,245802,2021/5/9 9:58,59051.93,59132.76,59046.10,59112.66,43.712205,0.001226
247340,245803,2021/5/9 9:59,59103.93,59132.93,59067.35,59126.14,35.714933,0.001225

In [15]:
TOTAL_RANGE = data["ATRP"].max() - data["ATRP"].min()
AVERAGE = (data["ATRP"].max() + data["ATRP"].min()) / 2
data["ATRP_Diff"] = (data["ATRP"] - AVERAGE) / TOTAL_RANGE
data["ATRP_Diff"].min()
data

,Unnamed: 0,TimeStamp,Open,High,Low,Close,Volume,ATRP,ATRP_Diff
0,517,2020/11/19 10:00,17855.50,17939.55,17854.26,17907.59,414.673918,NaN,NaN
1,518,2020/11/19 10:01,17907.59,17941.59,17891.30,17923.53,173.585510,NaN,NaN
2,519,2020/11/19 10:02,17923.53,17944.69,17910.50,17926.59,112.092070,NaN,NaN
3,520,2020/11/19 10:03,17926.59,17937.26,17915.50,17919.95,72.432187,NaN,NaN
4,521,2020/11/19 10:04,17919.96,17926.86,17892.96,17924.51,138.997232,NaN,NaN
...,...,...,...,...,...,...,...,...,...
247336,245799,2021/5/9 9:55,59036.20,59059.18,59029.48,59053.52,21.634121,0.001227,-0.357411
247337,245800,2021/5/9 9:56,59053.52,59086.21,59031.07,59031.08,33.719035,0.001228,-0.357258
247338,245801,2021/5/9 9:57,59031.08,59057.70,59028.00,59051.93,30.339184,0.001227,-0.357464
247339,245802,2021/5/9 9:58,59051.93,59132.76,59046.10,59112.66,43.712205,0.001226,-0.357954
247340,245803,2021/5/9 9:59,59103.93,59132.93,59067.35,59126.14,35.714933,0.001225,-0.358069

In [21]:
%%time

# FILENAME = "Binance_BTC_1m.csv"
# data = pd.read_csv(FILENAME)
# optimization_arithmetic=[]
# for interval_for_bounds in tqdm(range(5,20)):
#     for sd in range(2,5):
#         records_df, final_profit = speedy_grid_trading(
#             data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
#         )
#         optimization_arithmetic.append([final_profit, "", interval_for_bounds, sd])

Wall time: 0 ns

In [2]:
%%time
# FILENAME = "Mild_Fluctuate_data.csv"
# FILENAME = "Increasing_Data.csv"
# FILENAME = "Binance_BTC_1m.csv"
FILENAME = "Decreasing_Data.csv"
data = pd.read_csv(FILENAME)
data
# optimization_RSV=[]
# for interval_for_rsv in tqdm(range(10, 60,5)):
#     for interval_for_bounds in range(5, 20,5):
#         for sd_parameter in range(2,5):
#             for grid_number in range(6, 40,4):
#                 records_df, final_profit = grid_trading(
#                     data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,GRID_NUMBER=grid_number
#                 )
#                 optimization_RSV.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter, grid_number])
#                 print(time.ctime())
# for grid_number in range(6, 40,4):
#     records_df, final_profit = grid_trading(
#         data, INTERVALS_FOR_RSV=30, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,GRID_NUMBER=grid_number
#     )
#     optimization_RSV.append([final_profit, 30, 15, 2, grid_number])
#     print(time.ctime())

Wall time: 32 ms

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,TimeStamp,Open,High,Low,Close,Volume
0,5000,125000,135620,2021/2/21 12:52,56530.69,56571.77,56523.90,56526.38,17.928238
1,5001,125001,135621,2021/2/21 12:53,56526.38,56590.00,56517.00,56550.01,25.635945
2,5002,125002,135622,2021/2/21 12:54,56550.00,56640.00,56542.94,56604.54,19.254883
3,5003,125003,135623,2021/2/21 12:55,56604.55,56613.83,56541.25,56569.16,18.708440
4,5004,125004,135624,2021/2/21 12:56,56572.71,56631.11,56544.52,56623.46,19.152437
...,...,...,...,...,...,...,...,...,...
14995,19995,139995,113194,2021/2/5 21:47,37963.72,37999.68,37963.71,37978.09,89.867376
14996,19996,139996,113195,2021/2/5 21:48,37978.08,38130.17,37971.29,38130.00,178.493656
14997,19997,139997,113196,2021/2/5 21:49,38127.43,38198.78,38084.69,38172.03,211.731013
14998,19998,139998,113197,2021/2/5 21:50,38172.02,38172.03,38079.23,38140.94,158.094804
14999,19999,139999,113198,2021/2/5 21:51,38137.56,38141.20,38075.29,38110.48,92.377754

In [4]:
# optimization_df = pd.DataFrame(
#     optimization_RSV,
#     columns=[
#         "FinalProfit",
#         "IntervalForRSV",
#         "IntervalForBounds",
#         "SDParameter",
#         "GridNumber",
#     ],
# )

In [5]:
# optimization_df.to_excel("Training_ArithmeticSequence_RSV_GridNumber_Updated.xlsx")
# optimization_df = pd.read_excel("Training_ArithmeticSequence_RSV_GridNumber.xlsx")
# optimization_df

In [6]:
# df = optimization_df[
#     optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
# ]
# SDParameter = df["SDParameter"].unique()
# IntervalForBounds = df["IntervalForBounds"].unique()
# IntervalForRSV = df["IntervalForRSV"].unique()
# FinalProfit = df["FinalProfit"].unique()
# GridNumber = df["GridNumber"].unique()

In [8]:
# sd = SDParameter
# sd

In [9]:
# ifb = IntervalForBounds
# ifb

In [10]:
# ifrsv = IntervalForRSV
# ifrsv

In [11]:
# fp = FinalProfit
# fp

In [12]:
# gn = GridNumber
# gn

In [3]:
%%time
from RSV_GridNumber_ATRP_Arithmetic import grid_trading, speedy_grid_trading
# FILENAME = "Decreasing_Data.csv"
# FILENAME = "Increasing_Data.csv"
# FILENAME = "Mild_Fluctuate_Data.csv"
# FILENAME = "Binance_BTC_1m.csv"
data = pd.read_csv(FILENAME)
records_df, final_profit = grid_trading(
    data, INTERVALS_FOR_RSV=30, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,GRID_NUMBER=6,
)
records_df["Hour"] = pd.to_datetime(records_df["Hour"])
records_df

Wall time: 19.9 s

,Action,Price,n,Cash,Profit,LowerBound,UpperBound,LowerGrid,UpperGrid,FluctuateRate,Hour
0,Buying,18380,5.0,8098,-91902,16811.151413,19635.912158,539.521317,176.834151,-0.239204,2020-12-12 11:22:00
1,Selling,18728,0.0,101737,1737,16862.391538,19649.279002,338.079687,338.079687,-0.272135,2020-12-13 10:30:00
2,Buying,18911,5.0,7182,-92818,16862.411567,19649.333194,52.758455,623.528359,-0.272007,2020-12-13 10:31:00
3,Selling,19137,0.0,102867,2867,16867.166529,19671.810187,488.601316,179.337120,-0.285537,2020-12-13 16:15:00
4,Buying,19340,5.0,6165,-93835,16867.146367,19671.914998,397.850115,269.855440,-0.285818,2020-12-13 16:16:00
...,...,...,...,...,...,...,...,...,...,...,...
91,Selling,61995,0.0,295430,195430,45137.186295,63876.466302,3615.227257,504.042937,-0.340540,2021-04-13 16:46:00
92,Buying,62610,4.0,44990,-55010,45136.900897,63877.339734,3675.323914,444.762944,-0.340450,2021-04-13 16:47:00
93,Selling,62951,0.0,296793,196793,44949.230560,64565.969518,4169.344308,108.604091,-0.345771,2021-04-14 00:29:00
94,Buying,63654,4.0,42178,-57822,44948.887887,64566.982655,3521.405567,753.281804,-0.346315,2021-04-14 00:30:00
95,Selling,63824,0.0,297474,197474,44866.927259,64819.037946,4310.480711,0.000000,-0.351876,2021-04-14 13:26:00

In [11]:
%%time
import numpy as np

# records_df = records_df.sort_values(by="Hour", ascending=True)
records_df["TransactionInterval"] = records_df["Hour"].diff()
records_df = records_df.dropna()
records_df.loc[:, "TransactionInterval"] = records_df["TransactionInterval"].apply(
    lambda x: x.seconds
)
records_df

Wall time: 7 ms

C:\Users\bizjun\Anaconda3\envs\AlgoTrading\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

,Action,Price,n,Cash,Profit,LowerBound,UpperBound,LowerGrid,UpperGrid,FluctuateRate,Hour,TransactionInterval
1,Selling,56251,0.0,100281,281,55371.780600,57850.835358,221.908533,221.908533,-0.462920,2021-02-22 15:44:00,10380
2,Buying,56744,1.0,43537,-56463,55372.049773,57850.861074,54.732964,389.585144,-0.462261,2021-02-22 15:45:00,60
3,Selling,57379,0.0,100917,917,54768.000487,57918.335430,306.002214,306.002214,-0.417201,2021-02-22 01:00:00,33300
4,Buying,57892,1.0,43025,-56975,54767.347142,57920.053608,12.408461,600.754842,-0.416536,2021-02-22 01:01:00,60
5,Buying,37315,2.0,25370,-74630,29307.694000,38943.652104,1377.777131,2361.442562,0.164146,2029-01-21 23:59:00,82680
6,Selling,37331,0.0,100032,32,29549.141172,37538.149417,2658.176512,0.000000,-0.001812,2005-02-21 15:49:00,57000
7,Buying,37590,2.0,24851,-75149,29525.753354,37608.349705,2673.895078,0.000000,-0.007536,2005-02-21 17:57:00,7680
8,Selling,37652,0.0,100156,156,29507.569792,37712.529104,2601.032369,0.000000,-0.048978,2005-02-21 20:57:00,10800
9,Buying,37853,2.0,24451,-75549,29489.905716,37866.632739,2613.345201,0.000000,-0.064069,2006-02-21 00:57:00,14400
10,Selling,39344,0.0,103140,3140,29274.166187,39349.959540,2563.467909,0.000000,-0.236745,2007-02-21 07:10:00,22380
11,Buying,39356,2.0,24428,-75572,29269.905411,39371.751444,2631.986280,0.000000,-0.218365,2007-02-21 07:40:00,1800
12,Selling,45602,0.0,115631,15631,27851.951818,45614.780461,4045.610030,0.000000,-0.316729,2010-02-21 20:32:00,46320
13,Buying,45567,2.0,24497,-75503,27852.503515,45620.678315,4163.200341,0.000000,-0.297080,2010-02-21 20:37:00,300
14,Selling,45899,0.0,116294,16294,28202.693904,46845.589935,4368.365896,0.000000,-0.297046,2011-02-21 19:36:00,82740
15,Buying,46441,2.0,23412,-76588,28203.026283,46846.641675,1759.820300,2590.106022,-0.300040,2011-02-21 19:37:00,60
16,Selling,47197,0.0,117806,17806,28303.947554,47227.027302,4180.603519,0.000000,-0.337221,2012-02-21 00:48:00,18660
17,Buying,47513,2.0,22781,-77219,28402.109870,47518.711368,4253.672726,0.000000,-0.332464,2012-02-21 04:51:00,14580
18,Selling,47617,0.0,118016,18016,28497.764276,47803.366314,4196.493947,0.000000,-0.347885,2012-02-21 08:56:00,14700
19,Buying,47955,2.0,22106,-77894,28560.824490,47961.853194,4254.762318,0.000000,-0.342082,2012-02-21 11:11:00,8100
20,Selling,48556,0.0,119218,19218,29695.082865,50762.533678,3238.391866,501.136728,-0.467492,2014-02-21 14:25:00,11640
21,Buying,49019,2.0,21179,-78821,29695.586066,50763.467083,3405.069403,340.598958,-0.466629,2014-02-21 14:26:00,60
22,Selling,49057,0.0,119294,19294,29868.114831,51163.136459,3628.859654,0.000000,-0.488774,2014-02-21 21:15:00,24540
23,Buying,49530,2.0,20234,-79766,29868.589321,51164.114657,3633.394907,0.000000,-0.488147,2014-02-21 21:16:00,60
24,Buying,58008,1.0,41992,-58008,51953.683087,60367.202735,1228.597853,1849.444104,0.097534,2029-03-21 23:59:00,9780
25,Selling,58749,0.0,100741,741,52105.306896,60039.888366,2426.063214,283.650074,0.024520,1930-03-21 18:30:00,66660
26,Buying,59330,1.0,41411,-58589,52105.232374,60040.222035,2524.716517,185.708870,0.024737,1930-03-21 18:31:00,60
27,Selling,59377,0.0,100788,788,52189.690956,60951.971509,2625.982598,0.000000,-0.100925,2002-04-21 11:37:00,61560
28,Buying,60000,1.0,40788,-59212,52189.628192,60952.122418,2371.184484,253.076147,-0.101536,2002-04-21 11:38:00,60
29,Selling,60695,0.0,101483,1483,54322.625167,60744.777222,632.713449,632.713449,-0.408877,2010-04-21 12:21:00,2580
30,Buying,60722,1.0,40761,-59239,54340.393522,60742.395282,623.018383,664.068900,-0.396866,2010-04-21 12:41:00,1200
31,Selling,62377,0.0,103138,3138,55695.325335,62463.517689,1231.137269,0.000000,-0.454299,2014-04-21 22:14:00,34380
32,Buying,62561,1.0,40576,-59424,55642.790703,62607.168072,1314.238795,0.000000,-0.433874,2015-04-21 01:59:00,13500
33,Selling,62763,0.0,103339,3339,55595.550943,62791.567297,1355.635159,0.000000,-0.434839,2015-04-21 08:33:00,23640
34,Buying,62778,1.0,40561,-59439,55578.380604,62848.868137,1398.368440,0.000000,-0.422995,2015-04-21 10:22:00,6540
35,Selling,62854,0.0,103415,3415,55558.405391,62922.388823,1393.176327,0.000000,-0.432436,2015-04-21 12:35:00,7980

In [50]:
# records_df.to_excel("TransactionHistory_ArithmeticSequence_RSV_GridNumber.xlsx")