In [1]:
%load_ext lab_black
%config Completer.use_jedi = False
import pandas as pd
from Grid_Tuning_geometric import grid_trading, speedy_grid_trading
from tqdm import tqdm
import time

In [2]:
%%time

FILENAME = "Binance_BTC_1m.csv"
data = pd.read_csv(FILENAME)
optimization=[]
for interval_for_bounds in tqdm(range(5,20)):
    for sd in range(2,5):
        records_df, final_profit = speedy_grid_trading(
            data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
        )
        optimization.append([final_profit, "", interval_for_bounds, sd])

100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [18:34<00:00, 74.33s/it]

Wall time: 18min 35s

In [3]:
# optimization=[]
# for interval_for_rsv in tqdm(range(10, 60)):
#     for interval_for_bounds in range(2, 20):
#         for sd_parameter in range(2,5):
#             records_df, final_profit = grid_trading(
#                 data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,
#             )
#             optimization.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter])
#             print(time.ctime())

In [4]:
optimization_df = pd.DataFrame(
    optimization,
    columns=["FinalProfit", "IntervalForRSV", "IntervalForBounds", "SDParameter",],
)

In [5]:
# optimization_df.to_excel("Geometric_Sequence_Training_Parameters.xlsx")
# optimization_df = pd.read_excel("Training.xlsx")
optimization_df

    FinalProfit IntervalForRSV  IntervalForBounds  SDParameter
0        146083                                 5            2
1        152521                                 5            3
2        113419                                 5            4
3        129581                                 6            2
4        120412                                 6            3
5        105766                                 6            4
6        134226                                 7            2
7        124318                                 7            3
8        111756                                 7            4
9        128901                                 8            2
10       111604                                 8            3
11       114050                                 8            4
12       134532                                 9            2
13       121695                                 9            3
14       120476                                 9            4
15       125333                                10            2
16       114289                                10            3
17       126836                                10            4
18       105352                                11            2
19       110367                                11            3
20       121966                                11            4
21        98945                                12            2
22       101481                                12            3
23       104411                                12            4
24       108350                                13            2
25       106021                                13            3
26       112721                                13            4
27       115603                                14            2
28       109425                                14            3
29       127460                                14            4
30       175860                                15            2
31       111953                                15            3
32       112201                                15            4
33       135392                                16            2
34        98963                                16            3
35       131530                                16            4
36       146562                                17            2
37       101003                                17            3
38       123926                                17            4
39       130927                                18            2
40       113972                                18            3
41       124300                                18            4
42       128440                                19            2
43       116183                                19            3
44       110768                                19            4

In [6]:
df = optimization_df[
    optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
]
SDParameter = df["SDParameter"].unique()
IntervalForBounds = df["IntervalForBounds"].unique()
IntervalForRSV = df["IntervalForRSV"].unique()
FinalProfit = df["FinalProfit"].unique()

In [7]:
SDParameter

array([2], dtype=int64)

In [8]:
IntervalForBounds

array([15], dtype=int64)

In [9]:
IntervalForRSV

array([''], dtype=object)

In [10]:
FinalProfit

array([175860], dtype=int64)

In [55]:
%%time
from Grid_Tuning_geometric import grid_trading, speedy_grid_trading

records_df, final_profit = speedy_grid_trading(
    data, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,
)
records_df["Hour"] = pd.to_datetime(records_df["Hour"])
records_df

Wall time: 15.2 s

,Action,Price,n,Cash,Profit,LowerBound,UpperBound,Rate,Hour
0,Buying,18501,5.0,7495,-92505,17577.972772,19031.264112,0.006,2020-11-24 10:22:00
1,Selling,18631,0.0,100648,648,17659.514329,19019.645068,0.006,2020-11-24 17:22:00
2,Buying,18836,5.0,6470,-93530,17659.897028,19019.603399,0.006,2020-11-24 17:23:00
3,Selling,18971,0.0,101323,1323,17670.319483,19023.022992,0.006,2020-11-24 18:00:00
4,Buying,18971,5.0,6466,-93534,17673.913820,19024.399872,0.006,2020-11-24 18:12:00
...,...,...,...,...,...,...,...,...,...
5487,Selling,61656,0.0,272698,172698,45146.932863,63847.795213,0.006,2021-04-13 16:15:00
5488,Buying,62499,4.0,22702,-77298,45146.657911,63848.652872,0.006,2021-04-13 16:16:00
5489,Selling,62874,0.0,274199,174199,45116.448249,63936.214463,0.006,2021-04-13 17:51:00
5490,Buying,63503,4.0,20185,-79815,45116.063674,63937.261269,0.006,2021-04-13 17:52:00
5491,Selling,63919,0.0,275860,175860,44878.864310,64784.045463,0.006,2021-04-14 12:58:00

In [56]:
import numpy as np

# records_df = records_df.sort_values(by="Hour", ascending=True)
records_df["TransactionInterval"] = records_df["Hour"].diff()
records_df = records_df.dropna()
records_df.loc[:, "TransactionInterval"] = records_df["TransactionInterval"].apply(
    lambda x: x.seconds
)
records_df

C:\Users\bizjun\Anaconda3\envs\AlgoTrading\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

,Action,Price,n,Cash,Profit,LowerBound,UpperBound,Rate,Hour,TransactionInterval
1,Selling,18631,0.0,100648,648,17659.514329,19019.645068,0.006,2020-11-24 17:22:00,25200
2,Buying,18836,5.0,6470,-93530,17659.897028,19019.603399,0.006,2020-11-24 17:23:00,60
3,Selling,18971,0.0,101323,1323,17670.319483,19023.022992,0.006,2020-11-24 18:00:00,2220
4,Buying,18971,5.0,6466,-93534,17673.913820,19024.399872,0.006,2020-11-24 18:12:00,720
5,Selling,19088,0.0,101907,1907,17909.559924,19126.081784,0.006,2020-11-25 16:30:00,80280
...,...,...,...,...,...,...,...,...,...,...
5487,Selling,61656,0.0,272698,172698,45146.932863,63847.795213,0.006,2021-04-13 16:15:00,8040
5488,Buying,62499,4.0,22702,-77298,45146.657911,63848.652872,0.006,2021-04-13 16:16:00,60
5489,Selling,62874,0.0,274199,174199,45116.448249,63936.214463,0.006,2021-04-13 17:51:00,5700
5490,Buying,63503,4.0,20185,-79815,45116.063674,63937.261269,0.006,2021-04-13 17:52:00,60
5491,Selling,63919,0.0,275860,175860,44878.864310,64784.045463,0.006,2021-04-14 12:58:00,68760

In [58]:
# records_df.to_excel("TransactionHistory_GeometricSequence.xlsx")